# Generated by Django 2.1.7 on 2019-05-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Housework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housework_name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseworkCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['duedate'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_unique_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=45)),
                ('user_profile_image', models.TextField()),
                ('family_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FamilyMember', to='happyHouseServer.Family')),
            ],
        ),
        migrations.AddField(
            model_name='houseworkcheck',
            name='assignee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrentAssignee', to='happyHouseServer.User'),
        ),
        migrations.AddField(
            model_name='houseworkcheck',
            name='housework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Housework', to='happyHouseServer.Housework'),
        ),
        migrations.AddField(
            model_name='housework',
            name='assignee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignee', to='happyHouseServer.User'),
        ),
    ]
